package model;
// Generated Jun 27, 2017 8:48:39 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Budgetentry generated by hbm2java
 */
public class Budgetentry implements java.io.Serializable {

	private Integer idbudgetentry;
	private Budgetnomen budgetnomen;
	private Integer userid;
	private Integer periodicalid;
	private Integer type;
	private Date entrydate;
	private String comment;
	private BigDecimal moneyvalue;

	public Budgetentry() {
	}

	public Budgetentry(Budgetnomen budgetnomen, Integer userid, Integer periodicalid, Integer type, Date entrydate,
			String comment, BigDecimal moneyvalue) {
		this.budgetnomen = budgetnomen;
		this.userid = userid;
		this.periodicalid = periodicalid;
		this.type = type;
		this.entrydate = entrydate;
		this.comment = comment;
		this.moneyvalue = moneyvalue;
	}

	public Integer getIdbudgetentry() {
		return this.idbudgetentry;
	}

	public void setIdbudgetentry(Integer idbudgetentry) {
		this.idbudgetentry = idbudgetentry;
	}

	public Budgetnomen getBudgetnomen() {
		return this.budgetnomen;
	}

	public void setBudgetnomen(Budgetnomen budgetnomen) {
		this.budgetnomen = budgetnomen;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getPeriodicalid() {
		return this.periodicalid;
	}

	public void setPeriodicalid(Integer periodicalid) {
		this.periodicalid = periodicalid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getEntrydate() {
		return this.entrydate;
	}

	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public BigDecimal getMoneyvalue() {
		return this.moneyvalue;
	}

	public void setMoneyvalue(BigDecimal moneyvalue) {
		this.moneyvalue = moneyvalue;
	}

}
