package model;
// Generated Jun 27, 2017 8:48:39 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Budgetnomen generated by hbm2java
 */
public class Budgetnomen implements java.io.Serializable {

	private Integer idbudgetnomens;
	private Integer userid;
	private String name;
	private String comment;
	private Integer type;
	private Set budgetentries = new HashSet(0);

	public Budgetnomen() {
	}

	public Budgetnomen(Integer userid, String name, String comment, Integer type, Set budgetentries) {
		this.userid = userid;
		this.name = name;
		this.comment = comment;
		this.type = type;
		this.budgetentries = budgetentries;
	}

	public Integer getIdbudgetnomens() {
		return this.idbudgetnomens;
	}

	public void setIdbudgetnomens(Integer idbudgetnomens) {
		this.idbudgetnomens = idbudgetnomens;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Set getBudgetentries() {
		return this.budgetentries;
	}

	public void setBudgetentries(Set budgetentries) {
		this.budgetentries = budgetentries;
	}

}
