package model;
// Generated Jun 5, 2017 1:55:43 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Budgetentry generated by hbm2java
 */
public class Budgetentry implements java.io.Serializable {

	private Integer idbudgetentry;
	private Integer userid;
	private Integer nomenid;
	private Integer periodicalid;
	private Integer type;
	private Date entrydate;
	private String comment;

	public Budgetentry() {
	}

	public Budgetentry(Integer userid, Integer nomenid, Integer periodicalid, Integer type, Date entrydate,
			String comment) {
		this.userid = userid;
		this.nomenid = nomenid;
		this.periodicalid = periodicalid;
		this.type = type;
		this.entrydate = entrydate;
		this.comment = comment;
	}

	public Integer getIdbudgetentry() {
		return this.idbudgetentry;
	}

	public void setIdbudgetentry(Integer idbudgetentry) {
		this.idbudgetentry = idbudgetentry;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getNomenid() {
		return this.nomenid;
	}

	public void setNomenid(Integer nomenid) {
		this.nomenid = nomenid;
	}

	public Integer getPeriodicalid() {
		return this.periodicalid;
	}

	public void setPeriodicalid(Integer periodicalid) {
		this.periodicalid = periodicalid;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getEntrydate() {
		return this.entrydate;
	}

	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
