package model;
// Generated Jun 27, 2017 8:48:39 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer iduser;
	private String username;
	private String realnamefirst;
	private String realnamelast;
	private String email;
	private String picturelink;
	private String googleid;
	private String locale;
	private Date lastlogin;
	private Date registerdate;

	public User() {
	}

	public User(String username, String realnamefirst, String realnamelast, String email, String picturelink,
			String googleid, String locale, Date lastlogin, Date registerdate) {
		this.username = username;
		this.realnamefirst = realnamefirst;
		this.realnamelast = realnamelast;
		this.email = email;
		this.picturelink = picturelink;
		this.googleid = googleid;
		this.locale = locale;
		this.lastlogin = lastlogin;
		this.registerdate = registerdate;
	}

	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRealnamefirst() {
		return this.realnamefirst;
	}

	public void setRealnamefirst(String realnamefirst) {
		this.realnamefirst = realnamefirst;
	}

	public String getRealnamelast() {
		return this.realnamelast;
	}

	public void setRealnamelast(String realnamelast) {
		this.realnamelast = realnamelast;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPicturelink() {
		return this.picturelink;
	}

	public void setPicturelink(String picturelink) {
		this.picturelink = picturelink;
	}

	public String getGoogleid() {
		return this.googleid;
	}

	public void setGoogleid(String googleid) {
		this.googleid = googleid;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Date getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	public Date getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(Date registerdate) {
		this.registerdate = registerdate;
	}

}
